import type { Metadata } from 'next'
// These styles apply to every route in the application
import './globals.css'
import NavBar from './components/navbar'
import Sidebar from './components/sidebar'
import Footer from './components/footer'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=" min-h-screen">
        <NavBar></NavBar>
        <section className="flex ">
          <Sidebar></Sidebar>
          <div className="w-full min-h-auto">{children}</div>
        </section>
        <Footer></Footer>
      </body>
    </html>
  )
}
